pipeline {
  agent {
    label 'node1'
  }

  environment {
    IMAGE_NAME = "shippingservice"
    IMAGE_TAG = "latest"
    TRIVY_OUTPUT = "trivy-scan-report.txt"
    DOCKERHUB_USERNAME = "kemzzy"
  }


  stages {

    stage('Checkout code') {

      steps {
        git branch: 'main', url: 'https://github.com/Kemzzy-Dev/online-shop-ms-app'
      }
    }
    
    stage('Sonarqube Scan analysis') {
      environment {
        scannerHome = tool 'sonarqubescanner';
      }
      steps {
        withSonarQubeEnv(credentialsId: 'sonarqube', installationName: 'SonarQubeServer') {
          dir('src/shippingservice') {
            sh "${scannerHome}/bin/sonar-scanner"
          }
        }
      }
    }

    stage('Build Docker image') {
      steps {
        script {
          def image = docker.build("${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}", "./src/shippingservice")
        }
      }
    }

    stage('Scan Docker Image with Trivy') {
      steps {
        script {
          sh """
          trivy image \
          --format json \
          --output ${TRIVY_OUTPUT} \
          --severity HIGH,CRITICAL \
          ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}
          """
        }
      }
    }

    stage('Push Docker image') {
      steps {
        script {
          // empty because we are using dockerhub
          docker.withRegistry('', 'dockerhub-credentials') {
            docker.image("${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}").push()
          }
        }
      }
    }
  }
}