pipeline {
  agent {
    docker {image 'mcr.microsoft.com/dotnet/sdk:latest'}
  }

  stages {

    stage('Checkout code') {
      steps {
        git branch: 'main', url: 'https://github.com/Kemzzy-Dev/online-shop-ms-app'
      }
    }

    stage('SonarQube analysis') {
      steps {
        withSonarQubeEnv('SonarQubeServer') {
          sh "./gradlew sonar"
        }
      }
    }

    // stage('Build Docker image') {
    //   steps {
    //     script {
    //       def dockerfile = sh(script: 'cat Dockerfile', returnStdout: true).trim()

    //       def image = docker.build("your-dockerhub-username/your-image-name", "-f $dockerfile .")
    //     }
    //   }
    // }

    // stage('Push Docker image') {
    //   steps {
    //     script {
    //       docker.withRegistry('https://registry.hub.docker.com', 'your-dockerhub-username') {
    //         image.push('latest')
    //         image.push("${env.BUILD_NUMBER}")
    //         image.push("${env.BUILD_ID}")
    //       }
    //     }
    //   }
    // }
  }
}