pipeline {
  agent {
    docker {image 'golang'}
  }

  stages {

    stage('Checkout code') {
      steps {
        git branch: 'main', url: 'https://github.com/Kemzzy-Dev/online-shop-ms-app'
      }
    }

    stage('Install Java') {
      steps {
        sh 'apt-get update'
        sh 'apt-get install -y openjdk-17-jre'
      }
    }

    stage('SonarQube Analysis') {
      environment {
        scannerHome = tool 'sonarqubescanner';
      }
      steps {
        withSonarQubeEnv(credentialsId: 'sonarqube_token', installationName: 'SonarQubeServer') {
          sh "${scannerHome}/bin/sonar-scanner"
        }
      }
    }

    // stage('Build Docker image') {
    //   steps {
    //     script {
    //       def dockerfile = sh(script: 'cat Dockerfile', returnStdout: true).trim()

    //       def image = docker.build("your-dockerhub-username/your-image-name", "-f $dockerfile .")
    //     }
    //   }
    // }

    // stage('Push Docker image') {
    //   steps {
    //     script {
    //       docker.withRegistry('https://registry.hub.docker.com', 'your-dockerhub-username') {
    //         image.push('latest')
    //         image.push("${env.BUILD_NUMBER}")
    //         image.push("${env.BUILD_ID}")
    //       }
    //     }
    //   }
    // }
  }
}