pipeline {
  agent {
    label 'node1'
  }

  stages {

    stage('Checkout code') {

      when {
        changeset "src/checkoutservice/**"
      }

      steps {
        git branch: 'main', url: 'https://github.com/Kemzzy-Dev/online-shop-ms-app'
      }
    }
    
    stage('SonarQube analysis') {
      environment {
        scannerHome = tool 'sonarqubescanner';
      }
      steps {
        withSonarQubeEnv(credentialsId: 'sonarqube', installationName: 'SonarQubeServer') {
          dir('src/checkoutservice') {
            sh "${scannerHome}/bin/sonar-scanner"
          }
        }
      }
    }

    // stage('Install Java') {
    //   steps {
    //     sh 'apt-get update'
    //     sh 'apt-get install -y openjdk-17-jre'code
    //   }
    // }

    // stage('SonarQube Analysis') {
    //   agent {
    //     docker {image 'java:17-alpine'}
    //   }
      
    //   steps {
        
    //   }
    // }

    // stage('Build Docker image') {
    //   steps {
    //     script {
    //       def dockerfile = sh(script: 'cat Dockerfile', returnStdout: true).trim()

    //       def image = docker.build("your-dockerhub-username/your-image-name", "-f $dockerfile .")
    //     }
    //   }
    // }

    // stage('Push Docker image') {
    //   steps {
    //     script {
    //       docker.withRegistry('https://registry.hub.docker.com', 'your-dockerhub-username') {
    //         image.push('latest')
    //         image.push("${env.BUILD_NUMBER}")
    //         image.push("${env.BUILD_ID}")
    //       }
    //     }
    //   }
    // }
  }
}