name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/adservice/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'src/adservice'

      - name: Run SonarQube analysis
        uses: sonarsource/sonarqube-scan-action@v3.0.0
        with:
          sonarqube-token: ${{ secrets.SONARQUBE_TOKEN }}
          sonarqube-url: https://631b-105-116-10-105.ngrok-free.app/
          sonarqube-project-key: microservice-scan
          sonarqube-project-name: microservice scan

      - name: Build Docker image
        run: |
          docker build -t adservice:latest .

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: adservice:latest
          format: json
          output: trivy-output.json

    #   - name: Push image to DockerHub
    #     uses: docker/login-action@v1
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}
    #     run: |
    #       docker tag my-image ${{ secrets.DOCKER_USERNAME }}/my-image
    #       docker push ${{ secrets.DOCKER_USERNAME }}/my-image