name: Email Service CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/emailservice/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Navigate to src/emailservice
        run: |
          cd src/emailservice

      - name: Scan Code
        uses: sonarsource/sonarqube-scan-action@v3.1.0
        with:
          projectBaseDir: src/emailservice
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Build Docker image
        run: |
          docker build -t emailservice:latest .

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: emailservice:latest
          format: json
          output: trivy-output.json

      - name: Push Docker image
        run: |
          docker push emailservice:latest

    #   - name: Push image to DockerHub
    #     uses: docker/login-action@v1
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}
    #     run: |
    #       docker tag my-image ${{ secrets.DOCKER_USERNAME }}/my-image
    #       docker push ${{ secrets.DOCKER_USERNAME }}/my-image
